#version: "3.8"

services:
  copilot-be:                             # Nombre del servicio
    image: marialazaro/copilot:latest      # Nombre de la imagen a utilizar
    container_name: marifer # Nombre específico para el contenedor
    ports:
      - "8080:8080"  # Mapea el puerto 808# del host al 808# del contenedor
    environment:
      PORT: 8080     # Variable de entorno que Spring Boot leerá como `server.port`
      DATABASE_URL: "r2dbc:postgresql://ep-bitter-sunset-a8zocnvu-pooler.eastus2.azure.neon.tech/copilot?sslmode=require&channel_binding=require"
      DATABASE_USERNAME: "copilot_owner"
      DATABASE_PASSWORD: "npg_mhHyVb12LuCq"
      RAPIDAPI_URL: "https://copilot5.p.rapidapi.com/copilot"
      RAPIDAPI_HOST: "copilot5.p.rapidapi.com"
      RAPIDAPI_APIKEY: "41edba6ef7mshedaf8fb7c7e9442p1fc368jsn1274f29ade93"


# docker build -t marialazaro/copilot:latest . (construir)
# docker-compose up -d (correr en segundo plano)
# docker-compose down (parar y limpiar)
