server:
  port: 8080

spring:
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    #url: r2dbc:postgresql://ep-bitter-sunset-a8zocnvu-pooler.eastus2.azure.neon.tech/copilot?sslmode=require&channel_binding=require
    #username: copilot_owner
    #password: npg_mhHyVb12LuCq

rapidapi:
  url: ${RAPIDAPI_URL}
  host: ${RAPIDAPI_HOST}
  apikey: ${RAPIDAPI_APIKEY}
  #url: "https://copilot5.p.rapidapi.com/copilot"
  #host: "copilot5.p.rapidapi.com"
  #apikey: "41edba6ef7mshedaf8fb7c7e9442p1fc368jsn1274f29ade93"
  