# kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: marialazaro
type: Opaque
data:
  # Credenciales de la base de datos y RapidAPI en Base64
  DATABASE_URL: postgresql://ep-bitter-sunset-a8zocnvu-pooler.eastus2.azure.neon.tech/copilot?sslmode=require&channel_binding=require
  DATABASE_USERNAME: copilot_owner
  DATABASE_PASSWORD: npg_mhHyVb12LuCq
  RAPIDAPI_URL: https://copilot5.p.rapidapi.com/copilot
  RAPIDAPI_HOST: copilot5.p.rapidapi.com
  RAPIDAPI_APIKEY: 41edba6ef7mshedaf8fb7c7e9442p1fc368jsn1274f29ade93

# echo -n "my-user" | base64
# echo -n "my-password" | base64
# echo "bXktdXNlcg==" | base64 --decode