# kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: marialazaro
type: Opaque
data:
  # Credenciales de la base de datos y RapidAPI en Base64
  DATABASE_URL:        cjJkYmM6cG9zdGdyZXNxbDovL2VwLWJpdHRlci1zdW5zZXQtYTh6b2NudnUtcG9vbGVyLmVhc3R1czIuYXp1cmUubmVvbi50ZWNoL2NvcGlsb3Q/c3NsbW9kZT1yZXF1aXJlJmNoYW5uZWxfYmluZGluZz1yZXF1aXJl
  DATABASE_USERNAME:   Y29waWxvdF9vd25lcg==
  DATABASE_PASSWORD:   bnBnX21oSHlWYjEyTHVDcQ==
  RAPIDAPI_URL:        aHR0cHM6Ly9jb3BpbG90NS5wLnJhcGlkYXBpLmNvbS9jb3BpbG90
  RAPIDAPI_HOST:       Y29waWxvdDUucC5yYXBpZGFwaS5jb20=
  RAPIDAPI_APIKEY:     NDFlZGJhNmVmN21zaGVkYWY4ZmI3YzdlOTQ0MnAxZmMzNjhqc24xMjc0ZjI5YWRlOTM=


# echo -n "my-user" | base64
# echo -n "my-password" | base64
# echo "cjJkYmM6cG9zdGdyZXNxbDovL2VwLWJpdHRlci1zdW5zZXQtYTh6b2NudnUtcG9vbGVyLmVhc3R1czIuYXp1cmUubmVvbi50ZWNoL2NvcGlsb3Q/c3NsbW9kZT1yZXF1aXJlJmNoYW5uZWxfYmluZGluZz1yZXF1aXJl" | base64 --decode