name: Docker Hub

on:
  push:
    branches:
      - develop

jobs:
  dockerhub:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del código
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Login a Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build y Push con tags latest y SHA
      - name: Build and Push Docker Image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/copilot:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/copilot:${{ github.sha }}